import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { ChangeEvent, useState } from "react";
import { useAuth } from "@/hooks/auth";

export default function Home() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [registerUsername, setRegisterUsername] = useState("");
  const [registerPassword, setRegisterPassword] = useState("");
  const [registerEmail, setRegisterEmail] = useState("");
  const [registerName, setRegisterName] = useState("");
  const { user, setUser } = useAuth();

  const handleUsername = (e: ChangeEvent<HTMLInputElement>) => {
    setUsername(e.target.value);
  };

  const handlePassword = (e: ChangeEvent<HTMLInputElement>) => {
    setPassword(e.target.value);
  };

  const handleSubmit = async (e: SubmitEvent<HTMLFormElement>) => {
    e.preventDefault();
    const res = await fetch("/api/login", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ username, password }),
    });

    if (res.status === 200) {
      const session = await res.json();
      console.log(session);
      setUser(session.user);
    } else {
      console.log("login unsuccessful.");
    }
  };

  const handleRegisterSubmit = async (e: SubmitEvent<HTMLFormElement>) => {
    e.preventDefault();

    const res = await fetch("/api/register", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        username: registerUsername,
        password: registerPassword,
        email: registerEmail,
        name: registerName,
      }),
    });

    if (res.status === 200) {
      console.log("registered!");
      console.log(await res.json());
    } else {
      console.log("could not register.");
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {user ? (
          <p>Logged in as {user.name}</p>
        ) : (
          <div>
            <h3>Login</h3>
            <form onSubmit={handleSubmit}>
              <input
                onChange={handleUsername}
                placeholder="username"
                type="text"
                name="username"
                value={username}
              />
              <input
                onChange={handlePassword}
                placeholder="password"
                type="password"
                name="password"
                value={password}
              />
              <button type="submit">Log In</button>
            </form>

            <h3>Register</h3>
            <form onSubmit={handleRegisterSubmit}>
              <input
                onChange={(e: ChangeEvent<HTMLInputElement>) =>
                  setRegisterUsername(e.target.value)
                }
                placeholder="username"
                type="text"
                name="username"
                value={registerUsername}
              />
              <input
                onChange={(e: ChangeEvent<HTMLInputElement>) =>
                  setRegisterPassword(e.target.value)
                }
                placeholder="password"
                type="password"
                name="password"
                value={registerPassword}
              />
              <input
                onChange={(e: ChangeEvent<HTMLInputElement>) =>
                  setRegisterName(e.target.value)
                }
                placeholder="name"
                type="text"
                name="name"
                value={registerName}
              />
              <input
                onChange={(e: ChangeEvent<HTMLInputElement>) =>
                  setRegisterEmail(e.target.value)
                }
                placeholder="email"
                type="email"
                name="email"
                value={registerEmail}
              />
              <button type="submit">Register</button>
            </form>
          </div>
        )}
      </main>
    </>
  );
}
